# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

minFlow <- function(node_supplies, arc_src, arc_targ, arc_costs, arc_capacities) {
    .Call(`_minCostFlow_minFlow`, node_supplies, arc_src, arc_targ, arc_costs, arc_capacities)
}

