# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


#' @export
#' @rdname lemon-functions
GrossoLocatelliPullanMcRunner <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_GrossoLocatelliPullanMcRunner`, arcSources, arcTargets, numNodes)
}

#' Acquires bipartite partitions
#'
#' @param arcSources A vector of integers containing the source vertices of the edges
#' @param arcTargets A vector of integers containing the destination verctices of the edges
#' @param numNodes The number of nodes in the graph.
#' @return An R List containing (1) A boolean stating if the graph is bipartite, and (2) an std::vector of length numNodes, containing the partition for each node
#' @export
#' @rdname lemon-functions
getBipartitePartitions <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_getBipartitePartitions`, arcSources, arcTargets, numNodes)
}

#' Gets the topological sort on a list of graphs
#'
#' @return An R List containing (1) A boolean stating if the graph is a dag, and (2) an std::vector of length numNodes, containing the index of vertex i in the ordering at location i
#' @export
#' @rdname lemon-functions
getAndcheckTopologicalSort <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_getAndcheckTopologicalSort`, arcSources, arcTargets, numNodes)
}

#' Gets the topological sort on a list of graphs
#'
#' @return An R Numeric Vector of length numNodes, containing the index of vertex i in the ordering at location i.
#' @export
#' @rdname lemon-functions
getTopologicalSort <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_getTopologicalSort`, arcSources, arcTargets, numNodes)
}

#' Checks if a graph is connected
#'
#' @return  A boolean stating if we have a connected graph or not
#' @export
#' @rdname lemon-functions
IsConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsConnected`, arcSources, arcTargets, numNodes)
}

#' Checks if a graph is acyclic
#'
#' @return  A boolean stating if we have a connected graph or not
#' @export
#' @rdname lemon-functions
IsAcyclic <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsAcyclic`, arcSources, arcTargets, numNodes)
}

#' Checks if a graph is a tree
#'
#' @return  A boolean stating if we have a tree
#' @export
#' @rdname lemon-functions
IsTree <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsTree`, arcSources, arcTargets, numNodes)
}

#' Checks if a graph is bipartite
#'
#' @return  A boolean stating if we have a bipartite graph or not
#' @export
#' @rdname lemon-functions

IsBipartite <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsBipartite`, arcSources, arcTargets, numNodes)
}

#' Checks if a graph is strongly connected
#'
#' @param arcSources A vector of integers containing the source vertices of the edges
#' @param arcTargets A vector of integers containing the destination verctices of the edges
#' @param numNodes The number of nodes in the graph.
#' @return  A boolean stating if we have a strongly connected graph or not
#' @export
#' @rdname lemon-functions

IsStronglyConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsStronglyConnected`, arcSources, arcTargets, numNodes)
}

#' Checks if a graph is a DAG
#'
#' @return  A boolean stating if we have a DAG or not
#' @export
#' @rdname lemon-functions
IsDAG <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsDAG`, arcSources, arcTargets, numNodes)
}

#' Checks if a graph is bi-connected
#'
#' @return Stuff
#' @export
#' @rdname lemon-functions
IsBiNodeConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsBiNodeConnected`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
IsBiEdgeConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsBiEdgeConnected`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
IsLoopFree <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsLoopFree`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
IsParallelFree <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsParallelFree`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
IsSimpleGraph <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsSimpleGraph`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
IsEulerian <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_IsEulerian`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
CountBiEdgeConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_CountBiEdgeConnected`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
CountConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_CountConnectedComponents`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
CountBiNodeConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_CountBiNodeConnectedComponents`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
CountStronglyConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_CountStronglyConnectedComponents`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
FindStronglyConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_FindStronglyConnectedComponents`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
FindStronglyConnectedCutArcs <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_FindStronglyConnectedCutArcs`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
FindBiEdgeConnectedCutEdges <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_FindBiEdgeConnectedCutEdges`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
FindBiNodeConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_FindBiNodeConnectedComponents`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
FindBiNodeConnectedNodes <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_FindBiNodeConnectedNodes`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
FindConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_FindConnectedComponents`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
FindBiEdgeConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_FindBiEdgeConnectedComponents`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
MaximumWeightPerfectMatchingRunner <- function(arcSources, arcTargets, arcWeights, numNodes) {
    .Call(`_rlemon_MaximumWeightPerfectMatchingRunner`, arcSources, arcTargets, arcWeights, numNodes)
}

#' @export
#' @rdname lemon-functions
MaximumWeightFractionalPerfectMatchingRunner <- function(arcSources, arcTargets, arcWeights, numNodes) {
    .Call(`_rlemon_MaximumWeightFractionalPerfectMatchingRunner`, arcSources, arcTargets, arcWeights, numNodes)
}

#' @export
#' @rdname lemon-functions
MaximumWeightFractionalMatchingRunner <- function(arcSources, arcTargets, arcWeights, numNodes) {
    .Call(`_rlemon_MaximumWeightFractionalMatchingRunner`, arcSources, arcTargets, arcWeights, numNodes)
}

#' @export
#' @rdname lemon-functions
MaximumWeightMatchingRunner <- function(arcSources, arcTargets, arcWeights, numNodes) {
    .Call(`_rlemon_MaximumWeightMatchingRunner`, arcSources, arcTargets, arcWeights, numNodes)
}

#' @export
#' @rdname lemon-functions
MaximumCardinalityMatchingRunner <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_MaximumCardinalityMatchingRunner`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
MaximumCardinalityFractionalMatchingRunner <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_MaximumCardinalityFractionalMatchingRunner`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
CycleCancellingRunner <- function(arcSources, arcTargets, arcDistances, nodeSupplies, numNodes) {
    .Call(`_rlemon_CycleCancellingRunner`, arcSources, arcTargets, arcDistances, nodeSupplies, numNodes)
}

#' @export
#' @rdname lemon-functions
CapacityScalingRunner <- function(arcSources, arcTargets, arcDistances, nodeSupplies, numNodes) {
    .Call(`_rlemon_CapacityScalingRunner`, arcSources, arcTargets, arcDistances, nodeSupplies, numNodes)
}

#' @export
#' @rdname lemon-functions
CostScalingRunner <- function(arcSources, arcTargets, arcDistances, nodeSupplies, numNodes) {
    .Call(`_rlemon_CostScalingRunner`, arcSources, arcTargets, arcDistances, nodeSupplies, numNodes)
}

#' @export
#' @rdname lemon-functions
NetworkSimplexRunner <- function(arcSources, arcTargets, arcDistances, nodeSupplies, numNodes) {
    .Call(`_rlemon_NetworkSimplexRunner`, arcSources, arcTargets, arcDistances, nodeSupplies, numNodes)
}

#' @export
#' @rdname lemon-functions
HowardMmcRunner <- function(arcSources, arcTargets, arcDistances, numNodes) {
    .Call(`_rlemon_HowardMmcRunner`, arcSources, arcTargets, arcDistances, numNodes)
}

#' @export
#' @rdname lemon-functions
KarpMmcRunner <- function(arcSources, arcTargets, arcDistances, numNodes) {
    .Call(`_rlemon_KarpMmcRunner`, arcSources, arcTargets, arcDistances, numNodes)
}

#' @export
#' @rdname lemon-functions
HartmannOrlinMmcRunner <- function(arcSources, arcTargets, arcDistances, numNodes) {
    .Call(`_rlemon_HartmannOrlinMmcRunner`, arcSources, arcTargets, arcDistances, numNodes)
}

#' @export
#' @rdname lemon-functions
PlanarCheckingRunner <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_PlanarCheckingRunner`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
PlanarColoringRunner <- function(arcSources, arcTargets, numNodes, useFiveAlg = TRUE) {
    .Call(`_rlemon_PlanarColoringRunner`, arcSources, arcTargets, numNodes, useFiveAlg)
}

#' @export
#' @rdname lemon-functions
PlanarDrawingRunner <- function(arcSources, arcTargets, numNodes) {
    .Call(`_rlemon_PlanarDrawingRunner`, arcSources, arcTargets, numNodes)
}

#' @export
#' @rdname lemon-functions
ChristofidesRunner <- function(arcSources, arcTargets, arcDistances, numNodes, defaultEdgeWeight = 999999L) {
    .Call(`_rlemon_ChristofidesRunner`, arcSources, arcTargets, arcDistances, numNodes, defaultEdgeWeight)
}

#' @export
#' @rdname lemon-functions
GreedyTSPRunner <- function(arcSources, arcTargets, arcDistances, numNodes, defaultEdgeWeight = 999999L) {
    .Call(`_rlemon_GreedyTSPRunner`, arcSources, arcTargets, arcDistances, numNodes, defaultEdgeWeight)
}

#' @export
#' @rdname lemon-functions
InsertionTSPRunner <- function(arcSources, arcTargets, arcDistances, numNodes, defaultEdgeWeight = 999999L) {
    .Call(`_rlemon_InsertionTSPRunner`, arcSources, arcTargets, arcDistances, numNodes, defaultEdgeWeight)
}

#' @export
#' @rdname lemon-functions
NearestNeighborTSPRunner <- function(arcSources, arcTargets, arcDistances, numNodes, defaultEdgeWeight = 999999L) {
    .Call(`_rlemon_NearestNeighborTSPRunner`, arcSources, arcTargets, arcDistances, numNodes, defaultEdgeWeight)
}

#' @export
#' @rdname lemon-functions
Opt2TSPRunner <- function(arcSources, arcTargets, arcDistances, numNodes, defaultEdgeWeight = 999999L) {
    .Call(`_rlemon_Opt2TSPRunner`, arcSources, arcTargets, arcDistances, numNodes, defaultEdgeWeight)
}
