# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getBipartitePartitions <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_getBipartitePartitions`, arcSources, arcTargets, numNodes)
}

getAndcheckTopologicalSort <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_getAndcheckTopologicalSort`, arcSources, arcTargets, numNodes)
}

getTopologicalSort <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_getTopologicalSort`, arcSources, arcTargets, numNodes)
}

IsConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsConnected`, arcSources, arcTargets, numNodes)
}

IsAcyclic <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsAcyclic`, arcSources, arcTargets, numNodes)
}

IsTree <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsTree`, arcSources, arcTargets, numNodes)
}

IsBipartite <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsBipartite`, arcSources, arcTargets, numNodes)
}

IsStronglyConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsStronglyConnected`, arcSources, arcTargets, numNodes)
}

IsDAG <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsDAG`, arcSources, arcTargets, numNodes)
}

IsBiNodeConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsBiNodeConnected`, arcSources, arcTargets, numNodes)
}

IsBiEdgeConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsBiEdgeConnected`, arcSources, arcTargets, numNodes)
}

IsLoopFree <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsLoopFree`, arcSources, arcTargets, numNodes)
}

IsParallelFree <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsParallelFree`, arcSources, arcTargets, numNodes)
}

IsSimpleGraph <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsSimpleGraph`, arcSources, arcTargets, numNodes)
}

IsEulerian <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsEulerian`, arcSources, arcTargets, numNodes)
}

CountBiEdgeConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_CountBiEdgeConnected`, arcSources, arcTargets, numNodes)
}

CountConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_CountConnectedComponents`, arcSources, arcTargets, numNodes)
}

CountBiNodeConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_CountBiNodeConnectedComponents`, arcSources, arcTargets, numNodes)
}

CountStronglyConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_CountStronglyConnectedComponents`, arcSources, arcTargets, numNodes)
}

FindStronglyConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindStronglyConnectedComponents`, arcSources, arcTargets, numNodes)
}

FindStronglyConnectedCutArcs <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindStronglyConnectedCutArcs`, arcSources, arcTargets, numNodes)
}

FindBiEdgeConnectedCutEdges <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindBiEdgeConnectedCutEdges`, arcSources, arcTargets, numNodes)
}

FindBiNodeConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindBiNodeConnectedComponents`, arcSources, arcTargets, numNodes)
}

FindBiNodeConnectedNodes <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindBiNodeConnectedNodes`, arcSources, arcTargets, numNodes)
}

FindConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindConnectedComponents`, arcSources, arcTargets, numNodes)
}

FindBiEdgeConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindBiEdgeConnectedComponents`, arcSources, arcTargets, numNodes)
}

MaximumWeightPerfectMatchingRunner <- function(arcSources, arcTargets, arcWeights, numNodes) {
    .Call(`_test_MaximumWeightPerfectMatchingRunner`, arcSources, arcTargets, arcWeights, numNodes)
}

MaximumWeightFractionalPerfectMatchingRunner <- function(arcSources, arcTargets, arcWeights, numNodes) {
    .Call(`_test_MaximumWeightFractionalPerfectMatchingRunner`, arcSources, arcTargets, arcWeights, numNodes)
}

MaximumWeightFractionalMatchingRunner <- function(arcSources, arcTargets, arcWeights, numNodes) {
    .Call(`_test_MaximumWeightFractionalMatchingRunner`, arcSources, arcTargets, arcWeights, numNodes)
}

MaximumWeightMatchingRunner <- function(arcSources, arcTargets, arcWeights, numNodes) {
    .Call(`_test_MaximumWeightMatchingRunner`, arcSources, arcTargets, arcWeights, numNodes)
}

MaximumCardinalityMatchingRunner <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_MaximumCardinalityMatchingRunner`, arcSources, arcTargets, numNodes)
}

MaximumCardinalityFractionalMatchingRunner <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_MaximumCardinalityFractionalMatchingRunner`, arcSources, arcTargets, numNodes)
}

CycleCancellingRunner <- function(arcSources, arcTargets, arcDistances, nodeSupplies, numNodes) {
    .Call(`_test_CycleCancellingRunner`, arcSources, arcTargets, arcDistances, nodeSupplies, numNodes)
}

CapacityScalingRunner <- function(arcSources, arcTargets, arcDistances, nodeSupplies, numNodes) {
    .Call(`_test_CapacityScalingRunner`, arcSources, arcTargets, arcDistances, nodeSupplies, numNodes)
}

CostScalingRunner <- function(arcSources, arcTargets, arcDistances, nodeSupplies, numNodes) {
    .Call(`_test_CostScalingRunner`, arcSources, arcTargets, arcDistances, nodeSupplies, numNodes)
}

NetworkSimplexRunner <- function(arcSources, arcTargets, arcDistances, nodeSupplies, numNodes) {
    .Call(`_test_NetworkSimplexRunner`, arcSources, arcTargets, arcDistances, nodeSupplies, numNodes)
}

