# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getTopologicalSort <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_getTopologicalSort`, arcSources, arcTargets, numNodes)
}

IsConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsConnected`, arcSources, arcTargets, numNodes)
}

IsAcyclic <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsAcyclic`, arcSources, arcTargets, numNodes)
}

IsTree <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsTree`, arcSources, arcTargets, numNodes)
}

IsBipartite <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsBipartite`, arcSources, arcTargets, numNodes)
}

IsStronglyConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsStronglyConnected`, arcSources, arcTargets, numNodes)
}

IsDAG <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsDAG`, arcSources, arcTargets, numNodes)
}

IsBiNodeConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsBiNodeConnected`, arcSources, arcTargets, numNodes)
}

IsBiEdgeConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsBiEdgeConnected`, arcSources, arcTargets, numNodes)
}

IsLoopFree <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsLoopFree`, arcSources, arcTargets, numNodes)
}

IsParallelFree <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsParallelFree`, arcSources, arcTargets, numNodes)
}

IsSimpleGraph <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsSimpleGraph`, arcSources, arcTargets, numNodes)
}

IsEulerian <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_IsEulerian`, arcSources, arcTargets, numNodes)
}

CountBiEdgeConnected <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_CountBiEdgeConnected`, arcSources, arcTargets, numNodes)
}

CountConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_CountConnectedComponents`, arcSources, arcTargets, numNodes)
}

CountBiNodeConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_CountBiNodeConnectedComponents`, arcSources, arcTargets, numNodes)
}

CountStronglyConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_CountStronglyConnectedComponents`, arcSources, arcTargets, numNodes)
}

FindStronglyConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindStronglyConnectedComponents`, arcSources, arcTargets, numNodes)
}

FindStronglyConnectedCutArcs <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindStronglyConnectedCutArcs`, arcSources, arcTargets, numNodes)
}

FindBiEdgeConnectedCutEdges <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindBiEdgeConnectedCutEdges`, arcSources, arcTargets, numNodes)
}

FindBiNodeConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindBiNodeConnectedComponents`, arcSources, arcTargets, numNodes)
}

FindBiNodeConnectedNodes <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindBiNodeConnectedNodes`, arcSources, arcTargets, numNodes)
}

FindConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindConnectedComponents`, arcSources, arcTargets, numNodes)
}

FindBiEdgeConnectedComponents <- function(arcSources, arcTargets, numNodes) {
    .Call(`_test_FindBiEdgeConnectedComponents`, arcSources, arcTargets, numNodes)
}

